version: '3'
services: 
    postgres:
        image: 'postgres:12-alpine'
        environment: 
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:alpine'
    api: 
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /srv/node_modules
            - ./server:/srv
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        depends_on: 
            - postgres
    client: 
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /srv/node_modules
            - ./client:/srv
        stdin_open: true
    worker: 
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /srv/node_modules
            - ./worker:/srv
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        depends_on:
            - api 
            - client
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '3050:80'
        
        